### ISSUE TITLE
Python3.4 api error

### ISSUE THREAD

**Issue by ipretender** [sendpulse/sendpulse-rest-api-python#1]
SPApiProxy = PySendPulse(REST_API_ID, REST_API_SECRET, TOKEN_STORAGE)
  File "/Users/****/pysendpulse.py", line 61, in **init**
    m.update("{}::{}".format(user_id, secret))
TypeError: Unicode-objects must be encoded before hashing

**Comment by rishatsharafiev** [comment]
To fix this error modify that line by like this `m.update("{}::{}".format(user_id, secret).encode('utf-8'))` @ipretender @sendpulse

**Comment by sendpulse** [comment]
Fixed. Thank you for your attention and help.
