### ISSUE TITLE
set token file path where save token key file on creating PySendPulse instance

### ISSUE THREAD

**Issue by igorveremsky** [sendpulse/sendpulse-rest-api-python#18]
Is there possibility to change file path where store token key on creating `PySendPulse` instance?

**Comment by yakshup** [comment]
yes.. it creates an identifier and it always finds the same file. This file_name should be configurable.

**Comment by igorveremsky** [comment]
@yakshup great idea too

**Comment by iredun** [comment]
I tried fix that #21

**Comment by sendpulse** [comment]
Thank you for your help. We really appreciate it.
