### ISSUE TITLE
Please share pypi package name

### ISSUE THREAD

**Issue by SehgalDivij** [sendpulse/sendpulse-rest-api-python#3]
What is the name of the package I use to install this??
Please share directions on how to use this in my project. 
Currently clueless.

**Comment by rishatsharafiev** [comment]
@SehgalDivij There is no setup.py, therefore project can't be publish to pypi.

**Comment by SehgalDivij** [comment]
Never mind.
I copied the script manually

**Comment by sendpulse** [comment]
Done. Thanks to @rishatsharafiev
