### ISSUE TITLE
get_list_of_senders() not working

### ISSUE THREAD

**Issue by gvanbavi** [sendpulse/sendpulse-rest-api-python#33]
Hi Sendpulse,

Using this example:
https://github.com/sendpulse/sendpulse-rest-api-python/blob/master/pysendpulse/examples/sendpulse-rest-api-example.py#L92

SPApiProxy.get_list_of_senders()

Return the following error:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 1
----> 1 SPApiProxy.get_list_of_senders()

File ~/anaconda3/lib/python3.10/site-packages/pysendpulse/pysendpulse.py:480, in PySendPulse.get_list_of_senders(self)
    475 """ List of all senders
    476 
    477 @return: dictionary with response message
    478 """
    479 logger.info("Function call: get_senders")
--> 480 return self.__handle_result(self.__send_request('senders'))

File ~/anaconda3/lib/python3.10/site-packages/pysendpulse/pysendpulse.py:207, in PySendPulse.__handle_result(self, data)
    204 logger.debug("Handle result: {}".format(errors, ))
    206 # return object that maintains backward-compatibility
--> 207 result.update(errors)
    208 result.update({'data': result.copy()})
    209 return result

AttributeError: 'list' object has no attribute 'update'`

**Comment by anatolyrr** [comment]
Also `get_addessbook_info` is not working.

As far as I understood, this regression was introduced in this commit:

https://github.com/sendpulse/sendpulse-rest-api-python/commit/5d2f64c64025665a6e1cf5f5a428b71dc3ed182d, file `pysendpulse.py`, lines 207–208

**Comment by sendpulse** [comment]
Issue has been fixed.
Thank you.
